target 'Kaare-Platform' do

pod 'ReactiveCocoa', '~> 2.3.1'
pod 'GDataXML-HTML', '~> 1.1'
pod 'Kaare', :git => 'https://github.com/artemyarulin/Kaare.git', :commit => '9d229cdac2e62aa2e37b0c5b76109138c10a2016'

end

target 'Kaare-PlatformTests' do

pod 'OHHTTPStubs', '~> 3.1.5'
pod 'AGAsyncTestHelper', '~> 0.2.2'
pod 'Kaare', :git => 'https://github.com/artemyarulin/Kaare.git', :commit => '9d229cdac2e62aa2e37b0c5b76109138c10a2016'

end

